apiVersion: batch/v1
kind: Job
metadata:
  name: single-job-example
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 4 # number of retries before throwing error
  activeDeadlineSeconds: 5  # time to allow job to run
  template:
    spec:
      containers:
      - name: dabian
        image: debian
        command: ["/bin/bash",  "-c", "echo 'nila'"]
      restartPolicy: OnFailure
      #restartPolicy: Never


